name: SignEdit
version: 2.1
description: Ever made a mistake on a sign, and not wanted to take the sign down to fix it? Now you don't have to!
author: Timroden
authors: [ThundrRok, Cyprias]
website: http://dev.timroden.net/
main: net.timroden.signedit.SignEdit
database: false

commands:
    signedit:
        description: Allows you to edit a sign
permissions:
    signedit.edit:
        description: Allows you to use /signedit
        default: false       
    signedit.override:
        description: Allows users to override protections.
        default: op
        children:
            signedit.edit: true
            signedit.admin: true
    signedit.admin:
        description: Allows you to admin SignEdit
        default: op
    signedit.notify:
        description: Notifies anyone with this when a SignEdit update is available
        default: op     
        children: 
            signedit.edit: true